### ISSUE TITLE
compilation error on fedora 17 64-bit

### ISSUE THREAD

**Issue by nareshv** [khughitt/pyopenjpeg#1]
--- openjpeg install ---

-- Install configuration: ""
-- Installing: /usr/local/lib/openjpeg-2.0/OpenJPEGTargets.cmake
-- Installing: /usr/local/lib/openjpeg-2.0/OpenJPEGTargets-noconfig.cmake
-- Installing: /usr/local/lib/openjpeg-2.0/OpenJPEGConfig.cmake
-- Installing: /usr/local/share/doc/openjpeg-2.0/LICENSE
-- Installing: /usr/local/include/openjpeg-2.0/opj_config.h
-- Installing: /usr/local/lib/libopenjp2.so.2.0.0
-- Installing: /usr/local/lib/libopenjp2.so.6
-- Installing: /usr/local/lib/libopenjp2.so
-- Installing: /usr/local/include/openjpeg-2.0/openjpeg.h
-- Installing: /usr/local/include/openjpeg-2.0/opj_stdint.h
-- Installing: /usr/local/share/man/man3/libopenjp2.3
-- Installing: /usr/local/bin/opj_decompress
-- Removed runtime path from "/usr/local/bin/opj_decompress"
-- Installing: /usr/local/bin/opj_compress
-- Removed runtime path from "/usr/local/bin/opj_compress"
-- Installing: /usr/local/bin/opj_dump
-- Removed runtime path from "/usr/local/bin/opj_dump"
-- Installing: /usr/local/share/man/man1/opj_compress.1
-- Installing: /usr/local/share/man/man1/opj_decompress.1
-- Installing: /usr/local/share/man/man1/opj_dump.1

-- pyopenjpeg install ---

[pyopenjpeg]$ ls -l /usr/local/include/*.h
lrwxrwxrwx 1 root root 42 Nov 23 11:19 /usr/local/include/openjpeg.h -> /usr/local/include/openjpeg-2.0/openjpeg.h
lrwxrwxrwx 1 root root 44 Nov 23 11:19 /usr/local/include/opj_config.h -> /usr/local/include/openjpeg-2.0/opj_config.h
lrwxrwxrwx 1 root root 44 Nov 23 11:19 /usr/local/include/opj_stdint.h -> /usr/local/include/openjpeg-2.0/opj_stdint.h

[pyopenjpeg]$ python setup.py build_ext -i
running build_ext
cythoning openjpeg/src/decode.pyx to openjpeg/src/decode.c
building 'openjpeg.decode' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/openjpeg
creating build/temp.linux-x86_64-2.7/openjpeg/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c openjpeg/src/decode.c -o build/temp.linux-x86_64-2.7/openjpeg/src/decode.o
openjpeg/src/decode.c: In function ‘__pyx_f_8openjpeg_6decode_7Decoder__decode’:
openjpeg/src/decode.c:2212:3: error: unknown type name ‘opj_bool’
openjpeg/src/decode.c:2213:3: error: unknown type name ‘opj_bool’
openjpeg/src/decode.c:2344:30: error: ‘CODEC_JP2’ undeclared (first use in this function)
openjpeg/src/decode.c:2344:30: note: each undeclared identifier is reported only once for each function it appears in
openjpeg/src/decode.c:2356:30: error: ‘CODEC_J2K’ undeclared (first use in this function)
openjpeg/src/decode.c:2374:3: warning: implicit declaration of function ‘opj_create_decompress_v2’ [-Wimplicit-function-declaration]
openjpeg/src/decode.c:2374:19: warning: assignment makes pointer from integer without a cast [enabled by default]
openjpeg/src/decode.c:2383:3: warning: passing argument 2 of ‘opj_set_info_handler’ from incompatible pointer type [enabled by default]
In file included from openjpeg/src/decode.c:253:0:
/usr/local/include/openjpeg.h:1073:31: note: expected ‘opj_msg_callback’ but argument is of type ‘void (_)(char *, void *)’
openjpeg/src/decode.c:2392:3: warning: passing argument 2 of ‘opj_set_warning_handler’ from incompatible pointer type [enabled by default]
In file included from openjpeg/src/decode.c:253:0:
/usr/local/include/openjpeg.h:1082:31: note: expected ‘opj_msg_callback’ but argument is of type ‘void (_)(char _, void *)’
openjpeg/src/decode.c:2401:3: warning: passing argument 2 of ‘opj_set_error_handler’ from incompatible pointer type [enabled by default]
In file included from openjpeg/src/decode.c:253:0:
/usr/local/include/openjpeg.h:1091:31: note: expected ‘opj_msg_callback’ but argument is of type ‘void (_)(char *, void *)’
openjpeg/src/decode.c:2410:3: warning: implicit declaration of function ‘opj_setup_decoder_v2’ [-Wimplicit-function-declaration]
openjpeg/src/decode.c:2597:5: warning: implicit declaration of function ‘opj_decode_v2’ [-Wimplicit-function-declaration]
In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:14,
                 from openjpeg/src/decode.c:255:
openjpeg/src/decode.c: At top level:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:0,
                 from openjpeg/src/decode.c:256:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
error: command 'gcc' failed with exit status 1

**Comment by nareshv** [comment]
https://gist.github.com/4134216 

proposed fix

**Comment by khughitt** [comment]
Thanks, nareshv! Can you please submit a pull request?

**Comment by khughitt** [comment]
Fixed with https://github.com/khughitt/pyopenjpeg/commit/0f5b62fce2fbfd5bc6a9cf851ab164eb07f90cb6
